/**
 * Sanctum Prompt Bank — 150 local reflection prompts.
 * Prompts are rotated daily, tracked in DB to avoid repeats within 30 days.
 * Never fetched from a server. Never personalized without user input.
 */

export interface Prompt {
  id: number;
  text: string;
  category: 'reflection' | 'gratitude' | 'curiosity' | 'feeling' | 'memory' | 'intention';
}

export const PROMPTS: Prompt[] = [
  { id: 1, text: "What's sitting quietly in the back of your mind today?", category: "feeling" },
  { id: 2, text: "If today had a color, what would it be?", category: "reflection" },
  { id: 3, text: "What's one thing you did gently for yourself this week?", category: "gratitude" },
  { id: 4, text: "What do you wish someone had said to you today?", category: "feeling" },
  { id: 5, text: "Describe a moment from the last few days that deserves to be kept.", category: "memory" },
  { id: 6, text: "What are you carrying that you'd like to set down?", category: "reflection" },
  { id: 7, text: "What surprised you about yourself recently?", category: "curiosity" },
  { id: 8, text: "What small thing went right today?", category: "gratitude" },
  { id: 9, text: "If your body could talk, what would it say right now?", category: "feeling" },
  { id: 10, text: "What is something you keep putting off — and why?", category: "reflection" },
  { id: 11, text: "What do you want to remember about this period of your life?", category: "memory" },
  { id: 12, text: "What would you do tomorrow if you weren't afraid?", category: "intention" },
  { id: 13, text: "Whose voice in your head is the kindest? Whose is the loudest?", category: "reflection" },
  { id: 14, text: "What have you been pretending not to notice?", category: "curiosity" },
  { id: 15, text: "When did you last feel fully present? What were you doing?", category: "memory" },
  { id: 16, text: "What's a belief you held last year that you don't hold anymore?", category: "reflection" },
  { id: 17, text: "What does 'enough' look like for you today?", category: "intention" },
  { id: 18, text: "Name something you're grateful for that you rarely acknowledge.", category: "gratitude" },
  { id: 19, text: "What is something you're learning to let go of?", category: "reflection" },
  { id: 20, text: "If a friend described you to someone else, what do you think they'd say?", category: "curiosity" },
  { id: 21, text: "What do you want more of in your life that money can't buy?", category: "intention" },
  { id: 22, text: "What's the most honest thing you could say right now?", category: "feeling" },
  { id: 23, text: "What have you forgiven yourself for? What are you still working on?", category: "reflection" },
  { id: 24, text: "What does your ideal ordinary day look like?", category: "intention" },
  { id: 25, text: "What skill or quality in yourself have you been undervaluing?", category: "curiosity" },
  { id: 26, text: "What's something you've been doing on autopilot that deserves more attention?", category: "reflection" },
  { id: 27, text: "Write about a place that made you feel safe.", category: "memory" },
  { id: 28, text: "What does rest look like for you? Do you let yourself have it?", category: "feeling" },
  { id: 29, text: "What are you most proud of this month — even if it seems small?", category: "gratitude" },
  { id: 30, text: "What conversation have you been avoiding?", category: "reflection" },
  { id: 31, text: "What do you notice when you're at your best? What makes that version of you show up?", category: "curiosity" },
  { id: 32, text: "What would you do with one completely free, expectation-free day?", category: "intention" },
  { id: 33, text: "Who in your life makes you feel most like yourself?", category: "memory" },
  { id: 34, text: "What's something you've been hard on yourself about that you'd forgive someone else for?", category: "reflection" },
  { id: 35, text: "What are three things that happened this week that you'd normally overlook?", category: "gratitude" },
  { id: 36, text: "Where does your mind go when it's allowed to wander?", category: "curiosity" },
  { id: 37, text: "What's the difference between who you are and who you're trying to be?", category: "reflection" },
  { id: 38, text: "What part of your routine brings you the most peace?", category: "gratitude" },
  { id: 39, text: "What have you outgrown recently?", category: "reflection" },
  { id: 40, text: "Write about something you once thought you'd never get through, that you got through.", category: "memory" },
  { id: 41, text: "What does your emotional weather look like today?", category: "feeling" },
  { id: 42, text: "What are you most curious about right now?", category: "curiosity" },
  { id: 43, text: "What are you hoping for, quietly, without telling anyone?", category: "intention" },
  { id: 44, text: "What story do you keep telling yourself that might not be entirely true?", category: "reflection" },
  { id: 45, text: "What would it look like to be 10% kinder to yourself this week?", category: "intention" },
  { id: 46, text: "What has someone done for you recently that you haven't fully acknowledged?", category: "gratitude" },
  { id: 47, text: "If you could go back to a moment this month and stay in it longer, which would it be?", category: "memory" },
  { id: 48, text: "What are you trying to figure out?", category: "reflection" },
  { id: 49, text: "What does your creative energy want to make right now?", category: "curiosity" },
  { id: 50, text: "What boundaries have you set recently that you're proud of?", category: "reflection" },
  { id: 51, text: "Describe the texture of today.", category: "feeling" },
  { id: 52, text: "What would you love to hear from someone who knows you well?", category: "feeling" },
  { id: 53, text: "What does your gut know that your head hasn't caught up to yet?", category: "reflection" },
  { id: 54, text: "What have you made peace with this year?", category: "reflection" },
  { id: 55, text: "What's something you've been meaning to say to yourself?", category: "feeling" },
  { id: 56, text: "What felt important five years ago that doesn't matter anymore?", category: "reflection" },
  { id: 57, text: "When do you feel most alive?", category: "curiosity" },
  { id: 58, text: "What do you wish you could communicate that you struggle to put into words?", category: "feeling" },
  { id: 59, text: "What has recently shifted in how you see yourself?", category: "reflection" },
  { id: 60, text: "What is something you're learning to ask for?", category: "intention" },
  { id: 61, text: "What would you tell your past self from a year ago?", category: "reflection" },
  { id: 62, text: "What are you currently reading — in books, in people, in situations?", category: "curiosity" },
  { id: 63, text: "What part of your life feels most in alignment right now?", category: "reflection" },
  { id: 64, text: "What do you wish you'd done differently last week — with compassion, not judgment?", category: "reflection" },
  { id: 65, text: "What's one thing you're committed to noticing more this week?", category: "intention" },
  { id: 66, text: "What would you do today if you knew it would be enough?", category: "intention" },
  { id: 67, text: "What's something you love about the season you're in right now?", category: "gratitude" },
  { id: 68, text: "What is weighing on your chest that you haven't written down yet?", category: "feeling" },
  { id: 69, text: "Who has influenced the way you think that you've never thanked?", category: "gratitude" },
  { id: 70, text: "What's the most important question you're sitting with right now?", category: "curiosity" },
  { id: 71, text: "What have you been afraid to want?", category: "feeling" },
  { id: 72, text: "What does your inner critic sound like today? What would a kinder voice say instead?", category: "reflection" },
  { id: 73, text: "What's something small that has made a big difference in your life?", category: "gratitude" },
  { id: 74, text: "What are you still figuring out about yourself?", category: "curiosity" },
  { id: 75, text: "What does the next version of you look like?", category: "intention" },
  { id: 76, text: "What does home feel like right now?", category: "feeling" },
  { id: 77, text: "What are you done with?", category: "reflection" },
  { id: 78, text: "What habit or ritual has been quietly supporting you?", category: "gratitude" },
  { id: 79, text: "What feels unfinished in your life right now?", category: "reflection" },
  { id: 80, text: "What does your creative self need right now?", category: "curiosity" },
  { id: 81, text: "When was the last time you felt genuinely proud of yourself?", category: "memory" },
  { id: 82, text: "What are you hiding in plain sight?", category: "reflection" },
  { id: 83, text: "What would become possible if you stopped waiting?", category: "intention" },
  { id: 84, text: "Describe a relationship in your life that has changed recently.", category: "reflection" },
  { id: 85, text: "What sounds do you associate with feeling peaceful?", category: "memory" },
  { id: 86, text: "What are you healing from — even if you're not sure what it is yet?", category: "feeling" },
  { id: 87, text: "What's the last thing that genuinely made you laugh?", category: "gratitude" },
  { id: 88, text: "What does courage look like for you today — even a small, quiet version?", category: "intention" },
  { id: 89, text: "What are you choosing to believe about yourself these days?", category: "reflection" },
  { id: 90, text: "What would you make more room for in your life if you could?", category: "intention" },
  { id: 91, text: "What relationships are feeding you right now? What ones are draining you?", category: "reflection" },
  { id: 92, text: "What have you been learning about the kind of person you want to be?", category: "reflection" },
  { id: 93, text: "What moment this week do you want to hold onto?", category: "memory" },
  { id: 94, text: "What does your future self wish you would start today?", category: "intention" },
  { id: 95, text: "What would you do more of if you stopped worrying about whether you were good at it?", category: "curiosity" },
  { id: 96, text: "What truth are you slowly coming to terms with?", category: "reflection" },
  { id: 97, text: "What's something you've accepted about yourself that took a long time to accept?", category: "reflection" },
  { id: 98, text: "What are you trying to protect?", category: "feeling" },
  { id: 99, text: "What kind of energy do you want to bring into your day?", category: "intention" },
  { id: 100, text: "What story about your past has shaped how you move through the world?", category: "reflection" },
  { id: 101, text: "What do you need to hear right now that no one is saying?", category: "feeling" },
  { id: 102, text: "What's one thing you're curious to learn more about?", category: "curiosity" },
  { id: 103, text: "What do you notice about how you treat yourself when things are hard?", category: "reflection" },
  { id: 104, text: "What's something that scared you that you did anyway?", category: "memory" },
  { id: 105, text: "What is currently asking for your attention?", category: "reflection" },
  { id: 106, text: "How has your relationship with silence changed?", category: "reflection" },
  { id: 107, text: "What does your body need today?", category: "feeling" },
  { id: 108, text: "What are you saying yes to that you'd rather say no to? And vice versa?", category: "reflection" },
  { id: 109, text: "What would it look like to trust yourself more?", category: "intention" },
  { id: 110, text: "Name something ordinary in your life that is actually extraordinary.", category: "gratitude" },
  { id: 111, text: "What's the loudest thing in your life that isn't making a sound?", category: "feeling" },
  { id: 112, text: "What does growth feel like in your body, right now?", category: "reflection" },
  { id: 113, text: "What do you know now that you wish you'd known earlier?", category: "reflection" },
  { id: 114, text: "What's a small act of care you could offer yourself today?", category: "intention" },
  { id: 115, text: "What are you not ready to let go of yet — and is that okay?", category: "feeling" },
  { id: 116, text: "What do you love about how you move through the world?", category: "gratitude" },
  { id: 117, text: "What has been sitting in your drafts — in life, not just writing?", category: "reflection" },
  { id: 118, text: "What are you building, even when it doesn't feel like it?", category: "intention" },
  { id: 119, text: "Who do you want to call or write to?", category: "intention" },
  { id: 120, text: "What chapter of your life do you feel like you're in right now?", category: "reflection" },
  { id: 121, text: "What have you been tolerating that you'd like to change?", category: "reflection" },
  { id: 122, text: "What would your most rested self do differently today?", category: "intention" },
  { id: 123, text: "When did someone recently exceed your expectations?", category: "gratitude" },
  { id: 124, text: "What does safety feel like for you?", category: "feeling" },
  { id: 125, text: "What are you waiting for permission to do?", category: "curiosity" },
  { id: 126, text: "What is something you've been meaning to notice more?", category: "intention" },
  { id: 127, text: "What do you want the rest of this year to feel like?", category: "intention" },
  { id: 128, text: "What has changed in how you spend your time?", category: "reflection" },
  { id: 129, text: "What do you feel most tender about right now?", category: "feeling" },
  { id: 130, text: "What's something small you're looking forward to?", category: "gratitude" },
  { id: 131, text: "What needs to be said, to no one in particular?", category: "feeling" },
  { id: 132, text: "What part of growing up are you still working through?", category: "reflection" },
  { id: 133, text: "What does your intuition know that your logic hasn't caught up to?", category: "curiosity" },
  { id: 134, text: "When do you feel most at home in your body?", category: "feeling" },
  { id: 135, text: "What kind of love have you been receiving that you haven't fully let in?", category: "reflection" },
  { id: 136, text: "What would you create if it only had to be for you?", category: "curiosity" },
  { id: 137, text: "What does your anger have to teach you?", category: "reflection" },
  { id: 138, text: "What are you most excited about that you haven't told anyone yet?", category: "feeling" },
  { id: 139, text: "What is something you believe now that you didn't before?", category: "reflection" },
  { id: 140, text: "What have you been brave about recently, even quietly?", category: "memory" },
  { id: 141, text: "What does comfort look like for you right now?", category: "feeling" },
  { id: 142, text: "What would you like to understand better about yourself?", category: "curiosity" },
  { id: 143, text: "What are you grieving? What are you celebrating?", category: "feeling" },
  { id: 144, text: "What's one thing that is undeniably good in your life right now?", category: "gratitude" },
  { id: 145, text: "What are you grateful for about how far you've come?", category: "gratitude" },
  { id: 146, text: "What are you ready for?", category: "intention" },
  { id: 147, text: "What part of yourself have you been neglecting?", category: "reflection" },
  { id: 148, text: "What does your ideal relationship with yourself look like?", category: "intention" },
  { id: 149, text: "What are you holding more gently than before?", category: "reflection" },
  { id: 150, text: "What do you want to remember about who you are right now?", category: "memory" },
];

export const PROMPT_WINDOW_DAYS = 30;
